-- inserts organizaciones.tipo_organizacion
INSERT INTO organizaciones.tipo_organizacion(nombre, descripcion, codigo_abreviacion, activo, numero_orden,fecha_creacion, fecha_modificacion) VALUES ('Instituciones de educación superior','Instituciones de educación superior','IES', true,1, now(), now());

-- inserts organizaciones.tipo_relacion_organizaciones
INSERT INTO organizaciones.tipo_relacion_organizaciones(nombre, descripcion, codigo_abreviacion, activo, numero_orden,fecha_creacion, fecha_modificacion) VALUES ('Seccional','Seccional','SEC', true,1, now(), now());

-- inserts organizaciones.organizacion
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Nacional de Colombia - Bogotá',1,1,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Nacional de Colombia - Medellín',1,2,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Nacional de Colombia - Manizales',1,3,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Nacional de Colombia - Palmira',1,4,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Nacional de Colombia - Arauca',1,5,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Nacional de Colombia - Leticia',1,6,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Nacional de Colombia - San Andrés',1,7,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Nacional de Colombia - Tumaco',1,8,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Nacional de Colombia - La Paz',1,9,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Pedagógica Nacional',1,10,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Pedagógica y Tecnológica de Colombia - UPTC - Tunja',1,11,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Pedagógica y Tecnológica de Colombia - UPTC - Duitama',1,12,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Pedagógica y Tecnológica de Colombia - UPTC - Sogamoso',1,13,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Pedagógica y Tecnológica de Colombia - UPTC - Chinquiquirá',1,14,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Cauca',1,15,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Tecnológica de Pereira - UTP',1,16,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Caldas',1,17,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Córdoba',1,18,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Surcolombiana',1,19,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de la Amazonía',1,20,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Militar Nueva Granada',1,21,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Tecnológica del Choco Diego Luis Córdoba',1,22,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de los Llanos',1,23,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Popular del Cesar - Valledupar',1,24,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Popular del Cesar - Aguachica',1,25,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Colegio Mayor de Cundinamarca',1,26,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Pacífico',1,27,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Antioquía - Medellín',1,28,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Antioquía - El Carmen de Viboral',1,29,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Antioquía - Andes',1,30,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Antioquía - Caucasia',1,31,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Antioquía - Puerto Berrío',1,32,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Antioquía - Turbo',1,33,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Antioquía - Santafé de Antioquia',1,34,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Atlántico',1,35,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Valle - Cali',1,36,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Valle - Guadalajara de Buga',1,37,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Valle - Zarzal',1,38,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Valle - Buenaventura',1,39,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Valle - Palmira',1,40,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Industrial de Santander',1,41,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Cartagena',1,42,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Nariño',1,43,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Tolima',1,44,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Quíndio',1,45,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Francisco de Paula Santander - Cúcuta',1,46,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Francisco de Paula Santander - Ocaña',1,47,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Pamplona',1,48,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Magdalena - Unimagdalena',1,49,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Cundinamarca - UDEC - Fusagasugá',1,50,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Cundinamarca - UDEC - Giradot',1,51,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Cundinamarca - UDEC - Ubaté',1,52,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Sucre',1,53,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de la Guajira',1,54,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Distrital Francisco José de Caldas',1,55,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Pontificia Universidad Javeriana - Bogotá',1,56,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Pontificia Universidad Javeriana - Cali',1,57,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad INCCA de Colombia',1,58,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Santo Tomás - Bogotá',1,59,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Santo Tomás - Bucaramanga',1,60,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Santo Tomás - Tunja',1,61,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Externado de Colombia',1,62,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universidad de Bogotá - Jorge Tadeo Lozano - Bogotá',1,63,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universidad de Bogotá - Jorge Tadeo Lozano - Cartagena',1,64,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Central',1,65,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Pontificia Bolivariana - Medellín',1,66,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Pontificia Bolivariana - Bucaramanga',1,67,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Pontificia Bolivariana - Montería',1,68,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Pontificia Bolivariana - Palmira',1,69,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de la Sabana',1,70,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad EAFIT - Escuela de Administración, Finanzas e Instituto Tecnológico',1,71,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Norte',1,72,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Colegio Mayor de Nuestra Señora del Rosario',1,73,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universidad de América',1,74,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de San Buenaventura - Bogotá',1,75,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de San Buenaventura - Cali',1,76,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de San Buenaventura - Medellín',1,77,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de San Buenaventura - Cartagena',1,78,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Católica de Colombia - Bogotá',1,79,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Católica de Colombia - Chía',1,80,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Mariana',1,81,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Manizales',1,82,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universidad Autónoma de Colombia - FUAC',1,83,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Católica de Oriente - UCO',1,84,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Sergio Arboleda - Bogotá',1,85,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Sergio Arboleda - Santa Marta',1,86,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Bosque',1,87,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Boyacá - Uniboyaca',1,88,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Manuela Beltrán - Bogotá',1,89,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Manuela Beltrán - Bucaramanga',1,90,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad La Gran Colombia - Bogotá',1,91,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad La Gran Colombia - Armenia',1,92,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de la Salle',1,93,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Autónoma del Caribe - Uniautonoma - UAC',1,94,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Santiago de Cali - Cali',1,95,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Santiago de Cali - Palmira',1,96,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Libre - Bogotá',1,97,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Libre - Cali',1,98,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Libre - Barranquilla',1,99,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Libre - Pereira',1,100,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Libre - Cúcuta',1,101,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Libre - Socorro',1,102,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Medellín',1,103,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de los Andes',1,104,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Autónoma Latinoamericana - UNAULA',1,105,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universidad Piloto de Colombia - Bogotá',1,106,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universidad Piloto de Colombia - Girardot',1,107,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Cooperativa de Colombia - Bogotá',1,108,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Cooperativa de Colombia - Medellín',1,109,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Cooperativa de Colombia - Bucaramanga',1,110,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Cooperativa de Colombia - Barrancabermeja',1,111,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Cooperativa de Colombia - Santa Marta',1,112,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Autónoma de Bucaramanga - UNAB',1,113,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Metropolitana',1,114,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Autónoma de Manizales',1,115,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Antonio Nariño - Bogotá',1,116,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Antonio Nariño - Neiva',1,117,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Católica de Manizales',1,118,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Instituto Colombiano de Estudios Superiores de Incolda - ICESI',1,119,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Autónoma de Occidente - UAO',1,120,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Ibagué',1,121,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Tecnológica de Bolívar',1,122,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Sinú - Elías Bechara Zainúm - UNISINU - Montería',1,123,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad del Sinú - Elías Bechara Zainúm - UNISINU - Cartagena',1,124,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Ciencias Aplicadas y Ambientales - UDCA',1,125,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Nacional Abierta y a Distancia - UNAD',1,126,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Superior de Administración Pública - ESAP - Bogotá',1,127,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Superior de Administración Pública - ESAP - Medellín',1,128,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Dirección Nacinal de Escuelas',1,129,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Colegio Mayor de Antioquia',1,130,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Nacional del Deporte',1,131,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria del Valle - Instituto Departamental de Bellas Artes',1,132,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitario de la Paz',1,133,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Conservatorio del Tolima',1,134,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Politécnico Colombiano Jaime Isaza Cadavid',1,135,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Bellas Artes y Ciencias de Bolívar',1,136,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Unidad Central del Valle del Cauca - UCEVA',1,137,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria de Envigado - IUE',1,138,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Colegios de Colombia - UNICOC',1,139,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria de Ciencias de la Salud - FUCS',1,140,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Colegio de Estudios Superiores de Administración - CESA',1,141,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Juan Nepomuceno Corpas',1,142,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad CES',1,143,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria San Martín',1,144,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Monserrate - Unimonserrate',1,145,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Católica de Pereira',1,146,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Konrad Lorenz',1,147,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Los Libertadores',1,148,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria de Popayán - FUP',1,149,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Universitario de Historia de Colombia - Academia de Historia Colombiana',1,150,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Industrial de Santander - Fundación Universitaria de García Rovira, Norte y Gutierrez',1,151,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Católica Luis Amigó - FUNLAM',1,152,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Juan de Castellanos',1,153,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria María Cano',1,154,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Centro Universitario de Bienestar Rural',1,155,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Agraria de Colombia - Uniagraria',1,156,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria de San Gil - Unisangil',1,157,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Politécnico Grancolombiano',1,158,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria CEIPA',1,159,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria del Area Andina - Bogotá',1,160,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria del Area Andina - Pereira',1,161,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Escuela Colombiana de Rehabilitación',1,162,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Católica Lumen Gentium',1,163,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Católica del Norte',1,164,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria San Alfonso - FUSA',1,165,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Seminario Bíblico de Colombia',1,166,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Empresarial de la Cámara de Comercio de Bogotá',1,167,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación de Estudios Superiores Universitarios de Urabá Antonio Roldán Betancur',1,168,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Colombo Americana - UNICA',1,169,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación de Estudios Superiores - Monseñor Abraham Escudero Montoya - FUNDES',1,170,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Internacional del Trópico Americano - Unitrópico',1,171,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Cesmag - UNICESMAG',1,172,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Panamericana - Unipanamericana',1,173,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Sanitas',1,174,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Autónoma de las Américas',1,175,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Seminario Teológico Bautista Internacional - Unibautista',1,176,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Salazar y Herrera - IUSH',1,177,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Simón Bolívar - USB',1,178,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universidad de la Costa - CUC',1,179,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Colombiana de Ingeniería Julio Garavito',1,180,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Escuela de Administración de Negocios - EAN',1,181,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Escuela de Ingeniería de Antioquia - EIA',1,182,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Adventista - UNAC',1,183,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria de Santa Rosa de Cabal - UNISARC',1,184,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Lasallista',1,185,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Superior de Oftalmología del Instituto Barraquer de América',1,186,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria del Caribe - CECAR',1,187,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria de Colombia Ideas',1,188,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Rafael Nuñez - CURN',1,189,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria del Meta - Unimeta',1,190,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria del Huila - Corhuila',1,191,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Minuto de Dios - Uniminuto - Bogotá',1,192,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Minuto de Dios - Uniminuto - Bello',1,193,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Iberoamericana',1,194,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria de Ciencia y Desarrollo - Uniciencia',1,195,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad de Santander - UDES',1,196,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Remington',1,197,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universitaria Agustiniana - Uniagustiniana',1,198,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Cristiana Universitaria de San Andrés, Providencia y Santa Catalina',1,199,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Empresarial de Salamanca - CUES',1,200,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Republicana',1,201,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Colegiatura Colombiana',1,202,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Empresarial Alexander Von Humboldt - CUE',1,203,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Reformada - CUR',1,204,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporatión Universidad de Investigación y Desarrollo - UDI',1,205,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporatión Universitaria UNITEC',1,206,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporatión Universitaria Autónoma del Cauca',1,207,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporatión Universitaria Antonio José de Sucre - Corposucre',1,208,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela de Inteligencia Y Contrainteligencia Brigadier General Ricardo Charry Solano - ESICI',1,209,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela de Logística Ejercito Nacional',1,210,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela de Comunicaciones Militares - ESCOM',1,211,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Superior de Guerra General Rafael Reyes Prieto - ESDEGUE',1,212,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Centro de Educación Militar - CEMIL',1,213,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela de Postgrados de la Fuerza Aérea Colombiana Capitán José Edmundo Sandoval - EPFAC',1,214,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Superior de Educación Rural - ISER',1,215,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Tecnológica Colegio Mayor de Bolívar',1,216,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Colegio Mayor del Cauca',1,217,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Pascual Bravo',1,218,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Naval de Suboficiales ARC Barranquilla',1,219,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Tecnológico del Putumayo - Mocoa',1,220,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Tecnológico del Putumayo - Sibundoy',1,221,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria ITSA',1,222,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Unidades Tecnológicas de Santander - UTS',1,223,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Tecnológico de Antioquia',1,224,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Antonio José Camacho - UNIAJC',1,225,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Tecnológico Metropolitano - ITM',1,226,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Superior Tecnológica de Artes Débora Arango',1,227,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Tecnológica Autónoma de Bogotá - FABA',1,228,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Escuela Colombiana de Mercadotecnia - ESCOLME',1,229,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Tecnológico Comfenalco - Cartagena',1,230,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Centro Colombiano de Estudios Profesionales - CECEP',1,231,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Antonio de Arévalo - UNITECNAR',1,232,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Centro de Investigación, Docencia y Consultoria Administrativa - CIDCA',1,233,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria para el Desarrollo Humano - UNINPAHU',1,234,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Tecnológica Autónoma del Pacífico - UTAP',1,235,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución de Educación Superior Tecnológica FITEC',1,236,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación de Estudios Superiores Comfanorte - FESC',1,237,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Latina - Unilatina',1,238,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria ESUMER',1,239,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Eurocolombiana de Educación Superior - EUROCOL',1,240,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Tecnológica de Madrid - FTM',1,241,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Tecnológica Alberto Merani',1,242,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación de Estudios Tecnológicos del Norte del Valle - Cotecnova',1,243,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Centro Educacional de Cómputos y Sistemas - CEDESISTEMAS',1,244,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Centro Superior - UNICUCES',1,245,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto de Educación Empresarial - IDEE',1,246,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Escuela Superior de Administración y Estudios Tecnológicos - EAE',1,247,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto de Educación Superior Escuela de Tecnologías de Antioquia - ETdeA',1,248,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Tecnológica de Bogotá - CTB',1,249,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Superior de Ciencias Sociales y Económico Familiares - ICSEF',1,250,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Educativa ITAE',1,251,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación de Educación del Norte del Tolima - Coreducacion',1,252,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Marco Fidel Suárez - IUMAFIS',1,253,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Autónoma de Nariño - AUNAR',1,254,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Tecnológica Industrial Colombiana - TEINCO',1,255,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Academia Tecnológica de Colombia - ATEC',1,256,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Politécnico de la Costa Atlántica - PCA',1,257,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Politécnico Instituto Colombo Alemán para la Formación Tecnológica - ICAFT',1,258,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Unión Americana de Educación Superior - UNAES',1,259,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Superior de Ciencias Empresariales - ECIEM',1,260,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Internacional para el Desarrollo Educativo - CIDE',1,261,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Politécnico Santafé de Bogotá',1,262,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución de Educación Superior Tecnológica del Sur',1,263,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución de Educación Superior Corporación John F. Kennedy',1,264,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universal de Investigación y Tecnológica - CORUNIVERSITEC',1,265,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Comfacauca - Unicomfacauca',1,266,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Tecnológica Superior Siglo XXI',1,267,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Tecnológico Copacabana - TECO',1,268,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Tecnológica Católica de Occidente - TECOC',1,269,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela de Formación de Infanteria de Marina - EFIM',1,270,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Militar de Suboficiales Sargento Inocencio Chincá - EMSUB',1,271,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto de Educación Técnica Profesional de Roldanillo - INTEP',1,272,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Nacional de Formación Técnica Profesional de San Juan de Cesar- INFOTEP',1,273,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Nacional de Formación Técnica Profesional de San Andrés - INFOTEPSAI',1,274,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Técnico Agrícola - ITA',1,275,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Tecnológica Instituto Técnico Central - ITC',1,276,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Técnico Nacional de Comercio Simón Rodríguez - INTENALCO',1,277,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Tolimense de Formación Técnica Profesional - ITFIP',1,278,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto de Formación Técnica Profesional Humberto Velásquez García - ITFOTEPHVG',1,279,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Colegio Integrado Nacional Oriente de Caldas - IES CINOC',1,280,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Unidad Técnica Profesional de Sevilla - UNITEPS',1,281,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Academia de Dibujo Profesional - FADP',1,282,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación de Educación Superior San José - Usanjose',1,283,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación para la Educación Superior Real de Colombia',1,284,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Centro de Educación Superior Investigación y Profesionalización - CEDINPRO',1,285,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Escuela Colombiana de Hoteleria y Turismo - ECOTET',1,286,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Escuela de Administración y Mercadotecnia - EAM',1,287,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Politécnico Indoamericano',1,288,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación de Educación Superior Esatec',1,289,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Interamericana Técnica - FIT',1,290,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Instituto de Carreras Técnicas Profesionales - FIDCI',1,291,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación de Educación Superior Nueva América',1,292,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Horizonte - Unihorizonte',1,293,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación de Educación Superior Sikuani - FESI',1,294,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria San Mateo',1,295,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto de Educación Superior Politécnico Internacional',1,296,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Academia Superior de Artes',1,297,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Politécnico Colombo Andino',1,298,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación de Educación del Oriente',1,299,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Técnica de Colombia - CORPOTEC',1,300,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación centro de Estudios Artísticos y Técnicos - CEART',1,301,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Regional de Educación Superior - CRES',1,302,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Centro Técnico Arquitectónico',1,303,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria CENDA',1,304,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación de Estudios Superiores - Centro Internacional de Entrenamiento en urgencias y Emergencias Salamandra',1,305,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación de Educación Superior Suramericana',1,306,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Unificada Nacional de Educación Superior - CUN',1,307,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación de Educación Superior Miguel Camacho Perea',1,308,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Educativa del Litoral',1,309,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Latinoamericana - CUL',1,310,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Escuela de Artes y Letras',1,311,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Instituto de Administración y Finanzas - CIAF',1,312,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Regional del Caribe - IAFIC',1,313,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Educativa instituto Técnico Superior de Artes - IDEARTES',1,314,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Interamericana de Educación Superior - Corpocides',1,315,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Instituto Superior de Educación Socila - ISES',1,316,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Taller Cinco Centro de Diseño',1,317,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporacion Universitaria De Ciencias Empresariales, Educacion Y Salud - Corsalud',1,318,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporacion Bolivariana de Educación Superior - CORBES',1,319,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Escuela Tecnológica del Oriente',1,320,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Escuela Colombiana de Carreras Industriales - ECCI',1,321,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela de Investigación Criminal Teniente Coronel Elkin Molina Aldana - ESINC',1,322,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela de Suboficiales Fuerza Aérea CT. Andrés María Díaz D. - ESUFA',1,323,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Militar de Aviación Marco Fidel Suárez -  EMAVI',1,324,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Militar de Cadetes General José María Córdova - ESMIC',1,325,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Naval de Cadetes Almirante Padilla',1,326,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela de Ingenieros Militares - ESING',1,327,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Caro y Cuervo',1,328,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Instituto Tecnológico de Electrónica y Comunicaciones - ITEC',1,329,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Servicio Nacional de Aprendizaje - SENA - Bogotá',1,330,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Servicio Nacional de Aprendizaje - SENA - Cali',1,331,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Servicio Nacional de Aprendizaje - SENA - Medellín',1,332,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Servicio Nacional de Aprendizaje - SENA - Mosquera',1,333,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Servicio Nacional de Aprendizaje - SENA - Armenia',1,334,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Servicio Nacional de Aprendizaje - SENA - Buga',1,335,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Claretiana - Uniclaretiana',1,336,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Internacional de Estudios Superiores - INTER',1,337,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Americana',1,338,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Bellas Artes',1,339,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Colombo Internacional - Unicolombo',1,340,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Tecnológica Rural Coredi - FUNTEC',1,341,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Tecnológica Indoamericana',1,342,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria de Sabaneta - Unisabaneta',1,343,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Tecnológica Liderazgo Canadiense Internacional - LCI',1,344,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria CAFAM - Unicafam',1,345,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Cervantes San Agustín - Unicervantes',1,346,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria CIEO - Unicieo',1,347,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria de Colombia',1,348,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria U de Colombia',1,349,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Centro de Estudios Superiores María Goretti - Unicesmag',1,350,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Comfenalco Santander - UNC',1,351,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación de Educación Tecnológica Colsubsidio - Airbus Group',1,352,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Colombo Germana - UniGermana',1,353,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Escuela Tecnológica de Neiva Jesús Oviedo Pérez - FET',1,354,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria para el Desarrollo Empresarial y Social - CUDES',1,355,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Navarra - Uninavarra',1,356,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Luis G. Páez - Uniluisgpaez',1,357,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria de Asturias',1,358,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Escuela Latinoamericana de Ingenieros, Tecnólogos y Empresarios - ELITE',1,359,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Virtual Internacional - Uvirtual',1,360,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Conocimiento e Innovación para la Justicia - CIJ',1,361,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Tecnológico de Energía e Innovación E-Lernova',1,362,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Católica del Sur - Unicatolica del sur',1,363,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Comfamiliar',1,364,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria de Cataluña',1,365,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Internacional de Colombia - Unincol',1,366,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria de la Fundación Cardiovascular de Colombia - FCV',1,367,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Internacional de la Rioja - UNIR',1,368,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Digital de Antioquia - IUDigital',1,369,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Salesiana',1,370,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Universidad Autónoma Indígena Intercultural - UAIIN CRIC',1,371,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Institución Universitaria Comando de Educación y Doctrina del Ejército Nacional - CEDOC',1,372,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria Patricio Symes - Unisymes',1,373,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Fundación Universitaria San Pablo - Unisanpablo',1,374,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Centro de Estudios Aeronáuticos - CEA',1,375,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Unidad Tecnológica del Magdalena Medio – UTEM',1,376,true, now(), now());
INSERT INTO organizaciones.organizacion(nombre, tipo_organizacion, ente, activo, fecha_creacion, fecha_modificacion) VALUES ('Corporación Universitaria Autónoma del Norte',1,377,true, now(), now());